# Change these first
owner: congnews # Your GitHub organization or username, where this repository lives
repo: upuptime # The name of this repository
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
sites:
  - name: RSSHub
    url: $RSSHUB
  - name: Miniflux
    url: $Miniflux
  - name: FreshRSS
    url: $FreshRSS
  - name: Bark
    url: $BARK
    icon: https://s3.bmp.ovh/imgs/2023/09/18/8a1ac42b30390930.png
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: RSS Translator
    url: https://www.rsstranslator.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: OpenL
    url: https://openl.club
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cong.news
  #baseUrl: /upuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "让我看看谁挂了？"
  introMessage: "**欢迎来到我的监控网站！实时监控各个项目的运行情况。**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
